modLoader = "kotlinforforge"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "hexgender"
version = "${version}"
displayName = "HexGender"
authors = "TechTastic"
description = '''
A Hexcasting x Female Gender Mod Addon
'''
#logoFile = ""

[[dependencies.hexgender]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexgender]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexgender]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hexgender]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.11.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexgender]]
modId = "wildfire_gender"
mandatory = true
versionRange = "[1.20.1-3.0.1,)"
ordering = "NONE"
side = "BOTH"